<template>
  <div class="codex-overlay" @click.self="emit('close')">
    <div class="codex-panel">

      <!-- Header -->
      <div class="codex-header">
        <div class="codex-header-left">
          <span class="codex-tag">// </span>
          <span class="codex-title">CODEX</span>
          <span class="codex-subtitle">NETWATCH INTELLIGENCE DATABASE</span>
        </div>
        <button class="codex-close" @click="emit('close')" aria-label="Close codex">✕</button>
      </div>

      <!-- Tab navigation -->
      <div class="codex-tabs" role="tablist">
        <button
          v-for="tab in TABS"
          :key="tab.id"
          class="codex-tab"
          :class="{ 'codex-tab--active': activeTab === tab.id }"
          role="tab"
          :aria-selected="activeTab === tab.id"
          @click="activeTab = tab.id"
        >{{ tab.label }}</button>
      </div>

      <!-- Scrollable body -->
      <div class="codex-body" role="tabpanel">

        <!-- ── LORE ─────────────────────────────────────────────────────── -->
        <template v-if="activeTab === 'lore'">
          <section class="codex-lore">

            <h2 class="codex-h2">// THE NET</h2>
            <p class="codex-p">The Net is a vast virtual world interwoven with physical reality — a digital plane where data flows like blood through the veins of a dying city. Once maintained by the Megacorporations of the Old World, the Net now teeters on the edge of collapse.</p>

            <h2 class="codex-h2">// THE BLACKWALL</h2>
            <p class="codex-p">The Blackwall is a construct of impossible complexity — a firewalled boundary erected by NetWatch to quarantine the Rogue Artificial Intelligences that rampaged through the Net after the DataKrash of 2022. For decades it held. Now it bleeds.</p>
            <p class="codex-p">As Corporations and VDBs probe its integrity, fractures appear. Each crack becomes a <span class="codex-hl">Blackwall Gateway</span> — a breach through which Rogue AIs pour into defended space.</p>

            <h2 class="codex-h2">// NETWATCH</h2>
            <p class="codex-p">NetWatch is the last line of digital law enforcement — a Corporation dedicated to maintaining the integrity of the Net and destroying any AI that escapes the Blackwall. You are their most critical asset: a <span class="codex-hl">Core</span> node deep inside the Net, tasked with holding the line.</p>

            <h2 class="codex-h2">// YOUR MISSION</h2>
            <p class="codex-p">Deploy ICE protocols, Firewalls, and automated countermeasure towers across a <span class="codex-hl">51×51 tile grid</span>. Gather Eddies and Components from fallen intruders. Survive the waves. Close every Gateway. When the last breach is sealed and no Orchestrators remain — the Blackwall is restored.</p>

            <h2 class="codex-h2">// RESOURCES</h2>
            <div class="codex-table">
              <div class="codex-row">
                <span class="codex-key">€$ Eddies</span>
                <span class="codex-val">Primary currency. Build and upgrade towers, activate abilities. Generated by Harvesters networked to a Ping Tower.</span>
              </div>
              <div class="codex-row">
                <span class="codex-key">🔋 Components</span>
                <span class="codex-val">Secondary resource. Required for advanced towers and upgrades. Collected via Ping Towers from enemy drops, or converted from Eddies (100 €$ = 1 Component).</span>
              </div>
              <div class="codex-row">
                <span class="codex-key">Starting Pool</span>
                <span class="codex-val">500 Eddies · 5 Components</span>
              </div>
            </div>

            <h2 class="codex-h2">// WIN / LOSE</h2>
            <div class="codex-table">
              <div class="codex-row">
                <span class="codex-key codex-key--win">VICTORY</span>
                <span class="codex-val">Permanently close all Blackwall Gateways and eliminate every Orchestrator and AI Overlord on the field.</span>
              </div>
              <div class="codex-row">
                <span class="codex-key codex-key--lose">DEFEAT</span>
                <span class="codex-val">Core Health reaches 0. Rogue AIs have breached and consumed the node.</span>
              </div>
            </div>

            <h2 class="codex-h2">// WAVES</h2>
            <p class="codex-p">The Blackwall weakens every 5 waves — each fracture opens a new Gateway. Waves 1–10 are manually triggered; from Wave 11 the simulation auto-advances with a break window (30 sec at wave 10, reducing to 1 sec by wave 40). Skipping the break grants a <span class="codex-hl">2× Eddie generation boost</span> for 10 seconds. Boss waves (AI Overlord) appear every 10 waves from Wave 50.</p>

          </section>
        </template>

        <!-- ── TOWERS ────────────────────────────────────────────────────── -->
        <template v-if="activeTab === 'towers'">
          <article v-for="tower in TOWERS" :key="tower.id" class="codex-entry">
            <div class="codex-entry-head">
              <img :src="tower.image" :alt="tower.name" class="codex-entry-img" />
              <div class="codex-entry-head-text">
                <span class="codex-entry-name">{{ tower.name }}</span>
                <span class="codex-entry-role">{{ tower.role }}</span>
              </div>
            </div>
            <p class="codex-entry-desc">{{ tower.description }}</p>
            <div class="codex-table">
              <div v-for="stat in tower.stats" :key="stat.key" class="codex-row">
                <span class="codex-key">{{ stat.key }}</span>
                <span class="codex-val">{{ stat.val }}</span>
              </div>
            </div>
            <div v-if="tower.ability" class="codex-ability-badge">
              <span class="codex-ability-prefix">LV5 ABILITY —</span>
              <span class="codex-ability-name">{{ tower.ability }}</span>
            </div>
          </article>
        </template>

        <!-- ── ENEMIES ───────────────────────────────────────────────────── -->
        <template v-if="activeTab === 'enemies'">
          <article v-for="enemy in ENEMIES" :key="enemy.id" class="codex-entry codex-entry--enemy">
            <div class="codex-entry-head">
              <img :src="enemy.image" :alt="enemy.name" class="codex-entry-img codex-entry-img--enemy" />
              <div class="codex-entry-head-text">
                <span class="codex-entry-name codex-entry-name--enemy">{{ enemy.name }}</span>
                <span class="codex-entry-role">{{ enemy.tier }}</span>
              </div>
            </div>
            <p class="codex-entry-desc">{{ enemy.description }}</p>
            <div class="codex-table">
              <div v-for="stat in enemy.stats" :key="stat.key" class="codex-row">
                <span class="codex-key">{{ stat.key }}</span>
                <span class="codex-val">{{ stat.val }}</span>
              </div>
            </div>
            <div v-if="enemy.immunities.length" class="codex-immunity-row">
              <span class="codex-immunity-label">IMMUNE:</span>
              <span v-for="imm in enemy.immunities" :key="imm" class="codex-immunity-tag">{{ imm }}</span>
            </div>
          </article>
        </template>

      </div><!-- /codex-body -->
    </div><!-- /codex-panel -->
  </div><!-- /codex-overlay -->
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

// ── Tower images ──────────────────────────────────────────────────────────────
import imgIceWall       from '../../assets/towers/ICEWall.png'
import imgFirewall      from '../../assets/towers/FIREWall.png'
import imgDataspike     from '../../assets/towers/Dataspike.png'
import imgDaemonTurret  from '../../assets/towers/DaemonTurret.png'
import imgIceSniper     from '../../assets/towers/ICESniper.png'
import imgBlackwall     from '../../assets/towers/Blackwall.png'
import imgPing          from '../../assets/towers/Ping.png'
import imgHarvester     from '../../assets/towers/Harvestor.png'

// ── Enemy images ──────────────────────────────────────────────────────────────
import imgDataLeech         from '../../assets/enemies/DataLeech.png'
import imgCodeRunner        from '../../assets/enemies/CodeRunner.png'
import imgFwBreacher        from '../../assets/enemies/FIREWallBreacher.png'
import imgGlitch            from '../../assets/enemies/Glitch.png'
import imgOrchestrator      from '../../assets/enemies/Orchestrator.png'
import imgVdbNetrunner      from '../../assets/enemies/VDBNetRunner.png'
import imgSaboteur          from '../../assets/enemies/Saboteur.png'
import imgAiOverlord        from '../../assets/enemies/AIOverlord.png'

const emit = defineEmits<{ (e: 'close'): void }>()

// ── Tabs ───────────────────────────────────────────────────────────────────────
const TABS = [
  { id: 'lore',    label: '// LORE' },
  { id: 'towers',  label: '// TOWERS' },
  { id: 'enemies', label: '// ENEMIES' },
] as const

type TabId = typeof TABS[number]['id']
const activeTab = ref<TabId>('lore')

// ── Tower data (sourced from rulebook §5) ─────────────────────────────────────
const TOWERS = [
  {
    id: 'ice-wall',
    name: 'ICE Wall',
    role: 'Obstacle / Crowd Control',
    image: imgIceWall,
    description:
      'A hardened ICE protocol that slows nearby Rogue AIs and applies persistent damage. Acts as a physical barrier, forcing enemies to reroute. Cheap, durable — the backbone of any defence.',
    stats: [
      { key: 'HP',      val: '200 (level 1)' },
      { key: 'Range',   val: '1 tile (Chebyshev)' },
      { key: 'Damage',  val: '1 DPS to adjacent enemies' },
      { key: 'Slow',    val: '20% at level 1 → 50% at max' },
      { key: 'Cost',    val: '50 €$' },
    ],
    ability: 'EMP Blast — stuns all enemies within range',
  },
  {
    id: 'firewall',
    name: 'Firewall',
    role: 'Trap / Area Denial',
    image: imgFirewall,
    description:
      'A paired tower that creates a lethal gateway. Enemies passing through are stun-locked and shredded by data corruption. If either tower is destroyed, both collapse — detonating a burst of damage to all surrounding tiles.',
    stats: [
      { key: 'HP',         val: '500 per tower (level 1)' },
      { key: 'Placement',  val: '2 towers with 1 tile gap (horizontal / vertical / diagonal)' },
      { key: 'Damage',     val: '10 DPS through the gap' },
      { key: 'Effect',     val: 'Stun-locks enemies inside the gateway every tick' },
      { key: 'Cost',       val: '75 €$ + 1 Component' },
    ],
    ability: 'Tuned — bonus damage vs a player-selected enemy type',
  },
  {
    id: 'data-spike',
    name: 'Data Spike',
    role: 'Offensive / Line Damage',
    image: imgDataspike,
    description:
      'A directed assault protocol that fires data spikes in a fixed 90° cone. Direction is set at placement and cannot be changed. Pierces every enemy in the path — highly effective in packed corridors.',
    stats: [
      { key: 'HP',         val: '500 (level 1)' },
      { key: 'Range',      val: '2 tiles (level 1)' },
      { key: 'Damage',     val: '10 per spike — hits all enemies in path' },
      { key: 'Fire Rate',  val: '1 spike every 2 seconds' },
      { key: 'Cost',       val: '150 €$ + 2 Components' },
    ],
    ability: 'Overclock — temporarily increases fire rate',
  },
  {
    id: 'daemon-turret',
    name: 'Daemon Turret',
    role: 'Offensive / Multi-target',
    image: imgDaemonTurret,
    description:
      'A rotating autonomous turret that fires counter-daemon payloads at enemy concentrations. Each daemon damages every AI on the targeted tile. Best deployed on chokepoints swarming with weaker enemies.',
    stats: [
      { key: 'HP',         val: '100 (level 1)' },
      { key: 'Range',      val: '3 tiles (level 1)' },
      { key: 'Damage',     val: '10 per daemon to every enemy on target tile' },
      { key: 'Fire Rate',  val: '1 daemon every 2 seconds' },
      { key: 'Rotation',   val: '0.5° / tick (tracks targets)' },
      { key: 'Cost',       val: '5 Components' },
    ],
    ability: 'Overclock — temporarily increases fire rate',
  },
  {
    id: 'ice-sniper',
    name: 'ICE Sniper',
    role: 'Offensive / Single-target Sniper',
    image: imgIceSniper,
    description:
      'A long-range precision platform that reaches priority targets other towers cannot. Applies a slow on every hit. Cannot engage targets closer than 3 tiles — requires backup for close-range threats.',
    stats: [
      { key: 'HP',         val: '100 (level 1)' },
      { key: 'Range',      val: '3–5 tiles (minimum 3 tiles)' },
      { key: 'Damage',     val: '50 per shot, single target' },
      { key: 'Fire Rate',  val: '1 shot every 3 seconds' },
      { key: 'On-hit',     val: '20% slow for 2 seconds' },
      { key: 'Cost',       val: '10 Components' },
    ],
    ability: 'Overclock — temporarily increases fire rate',
  },
  {
    id: 'blackwall-tower',
    name: 'Blackwall Tower',
    role: 'Support / Blackwall Restoration',
    image: imgBlackwall,
    description:
      'The key to victory. Placed adjacent to a Gateway, it steadily drains the Gateway\'s HP until the breach is permanently sealed. Takes continuous damage while active — keep it repaired with Components and protect it with combat towers.',
    stats: [
      { key: 'HP',             val: '1000 (level 1)' },
      { key: 'Effect',         val: 'Closes adjacent Gateway over ~2 minutes (per tower, stacks)' },
      { key: 'Passive Damage', val: '−1000 HP per 2 min from each adjacent open Gateway' },
      { key: 'Auto-repair',    val: '10 Components consumed per full HP restore' },
      { key: 'Cost',           val: '20 Components' },
    ],
    ability: null,
  },
  {
    id: 'ping-tower',
    name: 'Ping Tower',
    role: 'Support / Resource Gathering',
    image: imgPing,
    description:
      'Extends the resource collection network. Harvests Component drops from defeated enemies within range, and enables connected Harvesters to relay Eddies to the player pool. The larger the network, the stronger the economy.',
    stats: [
      { key: 'HP',     val: '100 (level 1)' },
      { key: 'Range',  val: '3 tiles (level 1)' },
      { key: 'Effect', val: 'Collects Components pickups; activates Harvester income within range' },
      { key: 'Cost',   val: '2 Components' },
    ],
    ability: 'Oracle (permanent range boost) OR Boosted (Harvester Eddie boost) — mutually exclusive',
  },
  {
    id: 'harvester',
    name: 'Harvester',
    role: 'Support / Economy',
    image: imgHarvester,
    description:
      'Generates Eddies continuously when networked to a Ping Tower. Without a Ping connection, all generation is lost. Upgrading unlocks Component generation from level 3. Protect these at all costs — they fund your entire defence.',
    stats: [
      { key: 'HP',         val: '100 (level 1)' },
      { key: 'Generation', val: '1 Eddie / second (requires Ping Tower network)' },
      { key: 'Lv3+',       val: 'Also generates 1 Component every 10 seconds' },
      { key: 'Cost',       val: '2 Components' },
    ],
    ability: 'Overclock — temporarily boosts Eddie generation rate',
  },
]

// ── Enemy data (sourced from rulebook §7) ─────────────────────────────────────
const ENEMIES = [
  {
    id: 'data-leech',
    name: 'Data Leech',
    tier: 'Tier I — Standard',
    image: imgDataLeech,
    description:
      'The most basic Rogue AI — slow, weak, but relentless in number. Immune to both stuns and slows. Countered by ICE Wall damage and Data Spike pierce.',
    stats: [
      { key: 'HP',    val: '10 (level 1)' },
      { key: 'Damage', val: '5 (level 1)' },
      { key: 'Speed',  val: '0.5 tiles / sec' },
    ],
    immunities: ['Stun', 'Slow'],
  },
  {
    id: 'code-runner',
    name: 'Code Runner',
    tier: 'Tier II — Fast',
    image: imgCodeRunner,
    description:
      'Fragile but blindingly fast. Dangerous in large numbers due to speed. Can be slowed by ICE Wall and stunned by EMP Blast or Firewall gateway.',
    stats: [
      { key: 'HP',     val: '5 (level 1)' },
      { key: 'Damage', val: '10 (level 1)' },
      { key: 'Speed',  val: '1.0 tiles / sec' },
    ],
    immunities: [],
  },
  {
    id: 'firewall-breacher',
    name: 'Firewall Breacher',
    tier: 'Tier III — Tanky',
    image: imgFwBreacher,
    description:
      'A slow, armoured intrusion unit built to punch through passive defences. ICE Walls cannot slow it; Firewalls cannot stun it. Use Daemon Turrets or Data Spikes to bring it down.',
    stats: [
      { key: 'HP',     val: '50 (level 1)' },
      { key: 'Damage', val: '20 (level 1)' },
      { key: 'Speed',  val: '0.5 tiles / sec' },
    ],
    immunities: ['ICE Wall Slow', 'Firewall Stun'],
  },
  {
    id: 'glitch',
    name: 'Glitch',
    tier: 'Tier IV — Phase',
    image: imgGlitch,
    description:
      'An AI anomaly that phases straight through ICE Wall and Firewall tiles — ignoring their collision, slow, and stun effects entirely. Still takes full damage from active-fire towers. Ensure every lane has Data Spike or Daemon Turret coverage.',
    stats: [
      { key: 'HP',      val: '50 (level 1)' },
      { key: 'Damage',  val: '20 (level 1)' },
      { key: 'Speed',   val: '0.5 tiles / sec' },
      { key: 'Special', val: 'Phases through ICE Wall & Firewall tiles (no collision, no effect)' },
    ],
    immunities: [],
  },
  {
    id: 'orchestrator',
    name: 'Orchestrator',
    tier: 'Tier V — Mini-Boss',
    image: imgOrchestrator,
    description:
      'A command-class AI that spawns a Blackwall Gateway at its death location. Killing it changes the battlefield permanently — a new spawn point opens wherever it falls. High priority kill.',
    stats: [
      { key: 'HP',      val: '200 (level 1)' },
      { key: 'Damage',  val: '100 (level 1)' },
      { key: 'Speed',   val: '0.5 tiles / sec' },
      { key: 'On Death', val: 'Spawns a Blackwall Gateway at death tile' },
    ],
    immunities: ['ICE Wall DoT', 'Firewall Damage'],
  },
  {
    id: 'vdb-netrunner',
    name: 'VDB Netrunner',
    tier: 'Tier VI — Mini-Boss',
    image: imgVdbNetrunner,
    description:
      'A corporate saboteur that damages surrounding towers every tile it enters. All towers within 1 tile take 30 damage per tick as it advances. Use ICE Sniper to eliminate it at range before it shreds your economy.',
    stats: [
      { key: 'HP',     val: '750 (level 1)' },
      { key: 'Damage', val: '30 to Core (level 1)' },
      { key: 'Aura',   val: '30 damage to all towers within 1 tile, every tick' },
      { key: 'Speed',  val: '0.5 tiles / sec' },
    ],
    immunities: [],
  },
  {
    id: 'saboteur',
    name: 'Saboteur',
    tier: 'Tier VII — Disruptor',
    image: imgSaboteur,
    description:
      'An electronic warfare specialist. Pulses a disable field every 10 seconds, shutting down all towers within 1 tile for 5 seconds. Spread tower clusters and keep an ICE Sniper on overwatch.',
    stats: [
      { key: 'HP',      val: '500 (level 1)' },
      { key: 'Damage',  val: '20 (level 1)' },
      { key: 'Disable', val: 'All towers within 1 tile disabled for 5 sec, every 10 sec' },
      { key: 'Speed',   val: '0.5 tiles / sec' },
    ],
    immunities: [],
  },
  {
    id: 'ai-overlord',
    name: 'AI Overlord',
    tier: 'Tier VIII — Boss',
    image: imgAiOverlord,
    description:
      'The apex predator of the Rogue AI hierarchy. Three phases timed at 30-second intervals regardless of HP. Phase 1: fully immune, spawns Gateways. Phase 2: takes damage, spawns Glitches. Phase 3: takes +50% damage, spawns Orchestrators. Appears every 10 waves from Wave 50.',
    stats: [
      { key: 'HP',      val: '1000 (level 1)' },
      { key: 'Damage',  val: '50 (level 1)' },
      { key: 'Speed',   val: '0.5 tiles / sec' },
      { key: 'Phase 1', val: 'Immune to all damage — spawns Gateways every 5 tiles' },
      { key: 'Phase 2', val: 'Vulnerable — spawns Glitches every 5 tiles' },
      { key: 'Phase 3', val: '+50% damage received — spawns Orchestrators every 5 tiles' },
      { key: 'Appears', val: 'Every 10 waves starting from Wave 50' },
    ],
    immunities: [],
  },
]

// ── Keyboard support ───────────────────────────────────────────────────────────
function onKeyDown(e: KeyboardEvent): void {
  if (e.key === 'Escape') emit('close')
}
onMounted(() => window.addEventListener('keydown', onKeyDown))
onUnmounted(() => window.removeEventListener('keydown', onKeyDown))
</script>

<style scoped>
/* ── Overlay ──────────────────────────────────────────────────────────────────── */
.codex-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.78);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10200;
}

/* ── Panel ───────────────────────────────────────────────────────────────────── */
.codex-panel {
  background: rgba(2, 6, 22, 0.98);
  border: 1px solid #0044aa;
  border-radius: 2px;
  width: clamp(360px, 72vw, 960px);
  height: clamp(480px, 78vh, 860px);
  font-family: monospace;
  color: #00ccff;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  box-shadow: 0 0 40px rgba(0, 68, 170, 0.35), 0 0 80px rgba(0, 0, 0, 0.6);
}

/* ── Header ──────────────────────────────────────────────────────────────────── */
.codex-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14px 20px 12px;
  border-bottom: 1px solid #0044aa;
  flex-shrink: 0;
}

.codex-header-left {
  display: flex;
  align-items: baseline;
  gap: 8px;
}

.codex-tag {
  color: #ff3c28;
  font-size: 12px;
  font-weight: 700;
}

.codex-title {
  font-size: 14px;
  font-weight: 700;
  letter-spacing: 0.22em;
  color: #00ccff;
  text-transform: uppercase;
}

.codex-subtitle {
  font-size: 9px;
  letter-spacing: 0.18em;
  color: rgba(0, 204, 255, 0.4);
  text-transform: uppercase;
}

.codex-close {
  background: none;
  border: none;
  color: #ff3c28;
  font-size: 14px;
  cursor: pointer;
  padding: 2px 4px;
  opacity: 0.7;
  transition: opacity 0.1s;
  line-height: 1;
}
.codex-close:hover { opacity: 1; }

/* ── Tabs ────────────────────────────────────────────────────────────────────── */
.codex-tabs {
  display: flex;
  border-bottom: 1px solid #0044aa;
  flex-shrink: 0;
}

.codex-tab {
  background: none;
  border: none;
  border-right: 1px solid #0044aa;
  padding: 10px 22px;
  font-family: monospace;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: rgba(0, 204, 255, 0.4);
  cursor: pointer;
  transition: color 0.12s, background 0.12s;
}
.codex-tab:last-child { border-right: none; }
.codex-tab:hover { color: #00ccff; background: rgba(0, 68, 170, 0.12); }
.codex-tab--active {
  color: #ffdd00;
  background: rgba(255, 221, 0, 0.06);
  border-bottom: 2px solid #ffdd00;
  margin-bottom: -1px;
}

/* ── Scrollable body ─────────────────────────────────────────────────────────── */
.codex-body {
  flex: 1;
  overflow-y: auto;
  padding: 24px 28px;
  scrollbar-width: thin;
  scrollbar-color: #0044aa transparent;
}
.codex-body::-webkit-scrollbar { width: 6px; }
.codex-body::-webkit-scrollbar-track { background: transparent; }
.codex-body::-webkit-scrollbar-thumb { background: #0044aa; border-radius: 3px; }

/* ── Lore section ────────────────────────────────────────────────────────────── */
.codex-lore { display: flex; flex-direction: column; gap: 0; }

.codex-h2 {
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.24em;
  color: rgba(0, 204, 255, 0.5);
  text-transform: uppercase;
  margin: 24px 0 10px;
}
.codex-h2:first-child { margin-top: 0; }

.codex-p {
  font-size: 12px;
  line-height: 1.7;
  color: rgba(0, 204, 255, 0.75);
  margin: 0 0 10px;
}

.codex-hl {
  color: #ffdd00;
  font-weight: 700;
}

/* ── Shared stat table ───────────────────────────────────────────────────────── */
.codex-table {
  display: flex;
  flex-direction: column;
  gap: 1px;
  margin: 8px 0 0;
  border: 1px solid rgba(0, 68, 170, 0.5);
  border-radius: 1px;
  overflow: hidden;
}

.codex-row {
  display: grid;
  grid-template-columns: 160px 1fr;
  gap: 12px;
  padding: 6px 12px;
  background: rgba(0, 20, 60, 0.35);
  font-size: 11px;
  line-height: 1.5;
}
.codex-row:nth-child(even) { background: rgba(0, 30, 80, 0.25); }

.codex-key {
  color: rgba(0, 204, 255, 0.55);
  letter-spacing: 0.06em;
  text-transform: uppercase;
  font-size: 10px;
  align-self: start;
  padding-top: 1px;
  white-space: nowrap;
}
.codex-key--win { color: #00ff88; }
.codex-key--lose { color: #ff2244; }

.codex-val {
  color: rgba(0, 204, 255, 0.85);
  font-size: 11px;
}

/* ── Entry cards (towers & enemies) ─────────────────────────────────────────── */
.codex-entry {
  border: 1px solid rgba(0, 68, 170, 0.5);
  border-radius: 2px;
  padding: 18px 20px 16px;
  margin-bottom: 16px;
  background: rgba(0, 10, 35, 0.4);
  transition: border-color 0.15s;
}
.codex-entry:last-child { margin-bottom: 0; }
.codex-entry:hover { border-color: rgba(0, 100, 220, 0.7); }
.codex-entry--enemy { border-color: rgba(170, 0, 0, 0.4); }
.codex-entry--enemy:hover { border-color: rgba(220, 40, 40, 0.7); }

.codex-entry-head {
  display: flex;
  align-items: center;
  gap: 16px;
  margin-bottom: 10px;
}

.codex-entry-img {
  width: 56px;
  height: 56px;
  object-fit: contain;
  flex-shrink: 0;
  border-radius: 4px;
  background: rgba(0, 20, 60, 0.6);
  padding: 6px;
  border: 1px solid rgba(0, 68, 170, 0.35);
  image-rendering: pixelated;
}

.codex-entry-img--enemy {
  border-color: rgba(170, 0, 0, 0.35);
  background: rgba(40, 5, 5, 0.6);
}

.codex-entry-head-text {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.codex-entry-name {
  font-size: 14px;
  font-weight: 700;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: #00ccff;
}
.codex-entry-name--enemy { color: #ff6644; }

.codex-entry-role {
  font-size: 9px;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: rgba(0, 204, 255, 0.38);
}

.codex-entry-desc {
  font-size: 11px;
  line-height: 1.65;
  color: rgba(0, 204, 255, 0.65);
  margin: 0 0 10px;
}

/* ── Ability badge ───────────────────────────────────────────────────────────── */
.codex-ability-badge {
  margin-top: 10px;
  padding: 5px 10px;
  border: 1px solid rgba(255, 221, 0, 0.25);
  border-radius: 1px;
  background: rgba(255, 221, 0, 0.04);
  font-size: 9px;
  letter-spacing: 0.16em;
  text-transform: uppercase;
}

.codex-ability-prefix {
  color: rgba(255, 221, 0, 0.5);
  margin-right: 4px;
}

.codex-ability-name {
  color: #ffdd00;
  font-weight: 700;
}

/* ── Immunity row ────────────────────────────────────────────────────────────── */
.codex-immunity-row {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 10px;
}

.codex-immunity-label {
  font-size: 9px;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: rgba(255, 100, 68, 0.6);
}

.codex-immunity-tag {
  font-size: 9px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  padding: 2px 8px;
  border: 1px solid rgba(255, 60, 40, 0.4);
  border-radius: 1px;
  background: rgba(255, 30, 10, 0.08);
  color: #ff6644;
}
</style>
